// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Reclamos.Infrastructure.Persistence.Migrations
{
    /// <summary>Motivo de derivación final de cada ejecución (SPEC §1). Escrita a mano: dotnet ef no corre en el equipo local.</summary>
    public partial class MotivoDerivacion : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "MotivoDerivacion",
                schema: "app",
                table: "Ejecucion",
                type: "nvarchar(40)",
                maxLength: 40,
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "MotivoDerivacion",
                schema: "app",
                table: "Ejecucion");
        }
    }
}
