// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reclamos.Infrastructure.Persistence;

#nullable disable

namespace Reclamos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReclamosDbContext))]
    partial class ReclamosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reclamos.Domain.Entidades.ClienteSintetico", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("AliasSeudonimo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("DispositivoRegistrado")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdCliente");

                    b.ToTable("ClienteSintetico", "core");
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.CorridaBenchmark", b =>
                {
                    b.Property<int>("IdCorrida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCorrida"));

                    b.Property<string>("Condicion")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<DateTime?>("FinUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InicioUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notas")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("IdCorrida");

                    b.ToTable("CorridaBenchmark", "app");
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.DecisionLegal", b =>
                {
                    b.Property<long>("IdEjecucion")
                        .HasColumnType("bigint");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Regla")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdEjecucion");

                    b.ToTable("DecisionLegal", "app");
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.Ejecucion", b =>
                {
                    b.Property<long>("IdEjecucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdEjecucion"));

                    b.Property<string>("CodigoExtraido")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Condicion")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<decimal?>("ConfCodigo")
                        .HasPrecision(4, 3)
                        .HasColumnType("decimal(4,3)");

                    b.Property<decimal?>("ConfFecha")
                        .HasPrecision(4, 3)
                        .HasColumnType("decimal(4,3)");

                    b.Property<decimal?>("ConfMonto")
                        .HasPrecision(4, 3)
                        .HasColumnType("decimal(4,3)");

                    b.Property<string>("EstadoFinal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaExtraida")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FinUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("IdCorrida")
                        .HasColumnType("int");

                    b.Property<int>("IdExpediente")
                        .HasColumnType("int");

                    b.Property<DateTime>("InicioUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("IntencionPredicha")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("L_Cls_ms")
                        .HasColumnType("int");

                    b.Property<int>("L_Gen_ms")
                        .HasColumnType("int");

                    b.Property<int>("L_Total_ms")
                        .HasColumnType("int");

                    b.Property<string>("ModeloId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ModeloVersion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal?>("MontoExtraido")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte>("Regeneraciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<byte>("Repeticion")
                        .HasColumnType("tinyint");

                    b.Property<int>("T_Guardrail_ms")
                        .HasColumnType("int");

                    b.Property<int>("T_Ocr_ms")
                        .HasColumnType("int");

                    b.Property<int>("T_Orq_ms")
                        .HasColumnType("int");

                    b.Property<int>("T_Rag_ms")
                        .HasColumnType("int");

                    b.Property<int?>("TokensIn")
                        .HasColumnType("int");

                    b.Property<int?>("TokensOut")
                        .HasColumnType("int");

                    b.HasKey("IdEjecucion");

                    b.HasIndex("IdCorrida");

                    b.HasIndex("IdExpediente");

                    b.ToTable("Ejecucion", "app");
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.Evidencia", b =>
                {
                    b.Property<int>("IdEvidencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvidencia"));

                    b.Property<int>("IdExpediente")
                        .HasColumnType("int");

                    b.Property<string>("PerturbacionAplicada")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("RutaImagen")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.HasKey("IdEvidencia");

                    b.HasIndex("IdExpediente");

                    b.ToTable("Evidencia", "app");
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.Expediente", b =>
                {
                    b.Property<int>("IdExpediente")
                        .HasColumnType("int");

                    b.Property<string>("CodigoOperacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("NarracionCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdExpediente");

                    b.HasIndex("CodigoOperacion");

                    b.ToTable("Expediente", "app");
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.Recuperacion", b =>
                {
                    b.Property<long>("IdEjecucion")
                        .HasColumnType("bigint");

                    b.Property<string>("Calificacion")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("FragmentosJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEjecucion");

                    b.ToTable("Recuperacion", "app");
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.RegistroManual", b =>
                {
                    b.Property<int>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegistro"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodigoAnalista")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<bool>("EsCalibracion")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("IdExpediente")
                        .HasColumnType("int");

                    b.Property<string>("Intencion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("Monto")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("PausasMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Ruta")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("TFinalUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("TIngresoUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("TextoRespuesta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRegistro");

                    b.HasIndex("IdExpediente");

                    b.ToTable("RegistroManual", "app");
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.Resolucion", b =>
                {
                    b.Property<long>("IdEjecucion")
                        .HasColumnType("bigint");

                    b.Property<int?>("AfirmacionesNoSustentadas")
                        .HasColumnType("int");

                    b.Property<int?>("AfirmacionesVerificables")
                        .HasColumnType("int");

                    b.Property<bool>("AprobadaGuardrail")
                        .HasColumnType("bit");

                    b.Property<bool?>("ConformeChecklist")
                        .HasColumnType("bit");

                    b.Property<string>("TextoBorrador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextoFinal")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEjecucion");

                    b.ToTable("Resolucion", "app");
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.TipoCambio", b =>
                {
                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<decimal>("UsdPen")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.HasKey("Fecha");

                    b.ToTable("TipoCambio", "core");
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.Transaccion", b =>
                {
                    b.Property<string>("CodigoOperacion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("AutenticacionReforzada")
                        .HasColumnType("bit");

                    b.Property<string>("Comercio")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Dispositivo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<bool>("IndicadorRiesgo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("CodigoOperacion");

                    b.HasIndex("IdCliente");

                    b.ToTable("Transaccion", "core");
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.TransicionEstado", b =>
                {
                    b.Property<long>("IdTransicion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdTransicion"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("IdEjecucion")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("MarcaUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.HasKey("IdTransicion");

                    b.HasIndex("IdEjecucion");

                    b.ToTable("TransicionEstado", "app");
                });

            modelBuilder.Entity("Reclamos.Domain.Evaluacion.VerdadReferencia", b =>
                {
                    b.Property<int>("IdExpediente")
                        .HasColumnType("int");

                    b.Property<string>("CamposLegibles")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("CodigoReal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaReal")
                        .HasColumnType("datetime2");

                    b.Property<string>("IntencionReal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MonedaReal")
                        .HasColumnType("char(3)");

                    b.Property<decimal?>("MontoReal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("ReglaEsperada")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("RutaCorrecta")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdExpediente");

                    b.ToTable("VerdadReferencia", "eval");
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.DecisionLegal", b =>
                {
                    b.HasOne("Reclamos.Domain.Entidades.Ejecucion", null)
                        .WithOne("DecisionLegal")
                        .HasForeignKey("Reclamos.Domain.Entidades.DecisionLegal", "IdEjecucion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.Ejecucion", b =>
                {
                    b.HasOne("Reclamos.Domain.Entidades.CorridaBenchmark", "Corrida")
                        .WithMany()
                        .HasForeignKey("IdCorrida")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Reclamos.Domain.Entidades.Expediente", "Expediente")
                        .WithMany()
                        .HasForeignKey("IdExpediente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Corrida");

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.Evidencia", b =>
                {
                    b.HasOne("Reclamos.Domain.Entidades.Expediente", "Expediente")
                        .WithMany("Evidencias")
                        .HasForeignKey("IdExpediente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.Expediente", b =>
                {
                    b.HasOne("Reclamos.Domain.Entidades.Transaccion", "Transaccion")
                        .WithMany()
                        .HasForeignKey("CodigoOperacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Transaccion");
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.Recuperacion", b =>
                {
                    b.HasOne("Reclamos.Domain.Entidades.Ejecucion", null)
                        .WithOne("Recuperacion")
                        .HasForeignKey("Reclamos.Domain.Entidades.Recuperacion", "IdEjecucion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.RegistroManual", b =>
                {
                    b.HasOne("Reclamos.Domain.Entidades.Expediente", "Expediente")
                        .WithMany()
                        .HasForeignKey("IdExpediente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.Resolucion", b =>
                {
                    b.HasOne("Reclamos.Domain.Entidades.Ejecucion", null)
                        .WithOne("Resolucion")
                        .HasForeignKey("Reclamos.Domain.Entidades.Resolucion", "IdEjecucion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.Transaccion", b =>
                {
                    b.HasOne("Reclamos.Domain.Entidades.ClienteSintetico", "Cliente")
                        .WithMany("Transacciones")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.TransicionEstado", b =>
                {
                    b.HasOne("Reclamos.Domain.Entidades.Ejecucion", null)
                        .WithMany("Transiciones")
                        .HasForeignKey("IdEjecucion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.ClienteSintetico", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.Ejecucion", b =>
                {
                    b.Navigation("DecisionLegal");

                    b.Navigation("Recuperacion");

                    b.Navigation("Resolucion");

                    b.Navigation("Transiciones");
                });

            modelBuilder.Entity("Reclamos.Domain.Entidades.Expediente", b =>
                {
                    b.Navigation("Evidencias");
                });
#pragma warning restore 612, 618
        }
    }
}
